CREATE TABLE OKSUSU_ITEM ( 
    ITEM_CD    VARCHAR(10) PRIMARY KEY,
    ITEM_NM    VARCHAR(20),
    ITEM_DC    VARCHAR(1000),
    ITEM_TYPE  VARCHAR(10),
    PRICE      NUMERIC(18,0),
    GOOD       INT,
    VIEW_YN    VARCHAR(1),
    ORIGINAL_FILE_NAME VARCHAR(320),
    STORED_FILE_NAME   VARCHAR(260)
 );