CREATE TABLE [dbo].[OKSUSU_ITEM](
	[ITEM_CD] [nvarchar](10) NOT NULL,
	[ITEM_NM] [nvarchar](50) NOT NULL,
	[ITEM_DC] [nvarchar](1000) NOT NULL,
	[ORIGINAL_IMG_NAME] [nvarchar](260) NULL,
	[STORED_IMG_NAME] [nvarchar](36) NULL,
	[GOOD] [int] NULL,
	[INSERT_DT] [datetime] NOT NULL,
	[INSERT_ID] [nvarchar](30) NOT NULL,
	[PRICE] [numeric](18, 0) NULL,
	[ITEM_TYPE] [nvarchar](10) NULL,
	[VIEW_YN] [nvarchar](1) NULL,
PRIMARY KEY CLUSTERED 
(
	[ITEM_CD] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[OKSUSU_ITEM] ADD  DEFAULT (getdate()) FOR [INSERT_DT]
GO


