CREATE TABLE [dbo].[OKSUSU_USER](
	[ID] [nvarchar](20) NOT NULL,
	[PASSWORD] [nvarchar](100) NOT NULL,
	[NAME] [nvarchar](100) NOT NULL,
	[EMAIL] [nvarchar](100) NULL,
	[PHONE] [nvarchar](20) NULL,
	[ZIP] [nvarchar](10) NULL,
	[ADDR] [nvarchar](300) NULL,
	[ADMIN] [nvarchar](1) NULL,
 CONSTRAINT [PK_OKSUSU_USER] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[OKSUSU_USER] ADD  CONSTRAINT [DF_OKSUSU_USER_ADMIN]  DEFAULT ((0)) FOR [ADMIN]
GO


