CREATE TABLE [dbo].[OKSUSU_FILE](
	[IDX] [int] IDENTITY(1,1) NOT NULL,
	[BOARD_IDX] [int] NOT NULL,
	[ORIGINAL_FILE_NAME] [nvarchar](260) NOT NULL,
	[STORED_FILE_NAME] [nvarchar](36) NOT NULL,
	[FILE_SIZE] [int] NULL,
	[CREA_DTM] [date] NOT NULL,
	[CREA_ID] [nvarchar](30) NOT NULL,
	[DEL_GB] [nvarchar](1) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[IDX] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[OKSUSU_FILE] ADD  DEFAULT (getdate()) FOR [CREA_DTM]
GO

ALTER TABLE [dbo].[OKSUSU_FILE] ADD  DEFAULT ('N') FOR [DEL_GB]
GO

